sudo: required
services:
  - docker

before_install:
  - docker build -t sureshkorlapati/docker-react -f Dockerfile.dev .

script:
  - docker run sureshkorlapati/docker-react npm run test -- --coverage